name: axohack
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - pyarrow
  - zarr>=3
  - numcodecs
  - fsspec
  - aiohttp
  - matplotlib
  - scipy
  - ipykernel
  - jupyterlab
  - pyyaml
  - black
  - ruff
  - pytest
  - pip:
      - bleak>=1.1,<4
      - opencv-python>=5,<6
